# Generated by Django 2.0.4 on 2018-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=30, unique=True)),
                ('ucsd_email', models.CharField(max_length=50)),
            ],
        ),
    ]
