# Generated by Django 2.0.5 on 2018-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengerbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='convo_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='convo_step_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_events',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='ucsd_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
